import { readFile, writeFile, mkdir } from "node:fs/promises";
import { build } from "esbuild";

const root = new URL("../", import.meta.url);
const result = await build({
  entryPoints: [new URL("src/index.ts", root).pathname],
  bundle: true,
  format: "iife",
  platform: "browser",
  target: ["safari16.4", "chrome110"],
  minify: true,
  write: false,
});
const script = result.outputFiles[0]?.text;
if (!script) throw new Error("Terminal JavaScript bundle missing");
const xtermCss = await readFile(new URL("node_modules/@xterm/xterm/css/xterm.css", root), "utf8");
const localCss = await readFile(new URL("src/style.css", root), "utf8");
const html = `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; img-src data:; style-src 'unsafe-inline'; script-src 'unsafe-inline'; connect-src 'none'; frame-src 'none'; object-src 'none'; base-uri 'none'; form-action 'none'"><style>${xtermCss}\n${localCss}</style></head><body><div id="terminal"></div><script>${script}</script></body></html>`;
const dist = new URL("dist/", root);
await mkdir(dist, { recursive: true });
await writeFile(new URL("terminal.html", dist), html);
await writeFile(new URL("terminalHtml.ts", dist), `/* Generated by npm run build. */\nexport const terminalHtml = ${JSON.stringify(html)};\n`);
