#!/usr/bin/env python3
"""Verify generated agent runbook files stay in sync with their sources."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CANONICAL_RUNBOOK = ROOT / "CLAUDE.md"
DEPLOYMENT_NOTES = ROOT / "claude.md"
AGENT_POINTER = ROOT / "agent.md"
AGENTS_MIRROR = ROOT / "AGENTS.md"

AGENTS_PREFIX = """# APAS Agent Instructions

This file is generated from `claude.md` and mirrors deployment-only operational notes.
For the canonical team-mode contributor/agent runbook, read `CLAUDE.md`.

"""

AGENT_POINTER_CONTENT = """# APAS Agent Runbook Pointer

This file is generated by `scripts/check_agent_runbooks.py`.

Canonical team-mode contributor/agent runbook: `CLAUDE.md`.

`CLAUDE.md` is the source of truth for APAS architecture, team-mode roles,
local development, and contributor workflow. Update `CLAUDE.md` first for
runbook changes.

Deployment-only notes live in `claude.md`. `AGENTS.md` is generated from
`claude.md` for Codex-style agents that need deployment commands.

Run `python3 scripts/check_agent_runbooks.py` to verify these generated files.
"""


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def expected_agents_mirror() -> str:
    return AGENTS_PREFIX + read_text(DEPLOYMENT_NOTES)


def check_or_write(path: Path, expected: str, *, write: bool) -> list[str]:
    actual = read_text(path) if path.exists() else ""
    if actual == expected:
        return []
    if write:
        path.write_text(expected, encoding="utf-8")
        return []
    return [f"{path.relative_to(ROOT)} is out of sync"]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--write",
        action="store_true",
        help="rewrite generated files instead of only checking them",
    )
    args = parser.parse_args()

    errors: list[str] = []
    canonical = read_text(CANONICAL_RUNBOOK)
    deployment = read_text(DEPLOYMENT_NOTES)

    if "Canonical team-mode contributor/agent runbook" not in canonical:
        errors.append("CLAUDE.md must declare itself as the canonical runbook")
    if "Deployment-only operational notes" not in deployment:
        errors.append("claude.md must declare itself as deployment-only notes")

    errors.extend(
        check_or_write(AGENT_POINTER, AGENT_POINTER_CONTENT, write=args.write)
    )
    errors.extend(
        check_or_write(AGENTS_MIRROR, expected_agents_mirror(), write=args.write)
    )

    if errors:
        for error in errors:
            print(error, file=sys.stderr)
        print(
            "Run `python3 scripts/check_agent_runbooks.py --write` to regenerate mirrors.",
            file=sys.stderr,
        )
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
